2022-09-28 14:11:12 [model\pg.js] error: Error excuting query: error: relation "authentication.user" does not exist
    at Parser.parseErrorMessage (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2022-09-28 17:13:30 [model\pg.js] error: Error excuting query: error: relation "user_info" does not exist
    at Parser.parseErrorMessage (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (D:\Authnodejs\jobTech\NodeApi\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
